### ISSUE TITLE
trimming does not work

### ISSUE THREAD

**Issue by hoeferjanka** [hadasvolk/CompLabNGS#2]
I have an issue runing trimmomatic. It seems like I am missing a file to actually run the command. It says that it does not find one of teh files, however, if i list everything in my home directory, this file appears. 

I tried deleting ALL files in the environment and rerunning everything, the same issue appears. 
Anyone can help?

The commandline i am running: 
trimmomatic PE SRR1569760_sub_1.fastqc SRR1569760_sub_2.fastqc -baseout SRR1569760 ILLUMINACLIP:NexteraPE-PE.fa:2:30:10

This is the output:
TrimmomaticPE: Started with arguments:
 SRR1569760_sub_1.fastqc SRR1569760_sub_2.fastqc -baseout SRR1569760 ILLUMINACLIP:NexteraPE-PE.fa:2:30:10
Multiple cores found: Using 4 threads
Using templated Output files: SRR1569760_1P SRR1569760_1U SRR1569760_2P SRR1569760_2U
Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
ILLUMINACLIP: Using 1 prefix pairs, 4 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Exception in thread "main" java.io.FileNotFoundException: SRR1569760_sub_1.fastqc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:135)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:265)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

**Comment by hadasvolk** [comment]
You should specify the full name of the fastq files, if you haven't gzipped them
`trimmomatic PE SRR1569760_sub_1.fastq.gz SRR1569760_sub_2.fastq.gz -baseout SRR1569760 ILLUMINACLIP:NexteraPE-PE.fa:2:30:10`
