### ISSUE TITLE
GATK AddOrReplaceReadGroups activation (hw 6)

### ISSUE THREAD

**Issue by ranelmalka100** [hadasvolk/CompLabNGS#8]
Hello :) 
After a successful installation of GATK, I tried to run this command: 
$ gatk AddOrReplaceReadGroups -I "SRR1569760_vs_S288C.HQ.sort.bam" -O "out.bam" -LB READS -PL ILLUMINA -PU 1 -SM SRR1569760 --CREATE_INDEX 

but I got this error - 
```
Using GATK jar /home/nofar/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/nofar/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar AddOrReplaceReadGroups -I SRR1569760_vs_S288C.HQ.sort.bam -O out.bam -LB READS -PL ILLUMINA -PU 1 -SM SRR1569760 --CREATE_INDEX
Traceback (most recent call last):
  File "/home/nofar/gatk-4.5.0.0/gatk", line 511, in <module>
    main(sys.argv[1:])
  File "/home/nofar/gatk-4.5.0.0/gatk", line 177, in main
    runGATK(sparkRunner, sparkSubmitCommand, dryRun, gatkArgs, sparkArgs, javaOptions, debugPort, debugSuspend)
  File "/home/nofar/gatk-4.5.0.0/gatk", line 360, in runGATK
    runCommand(cmd, dryrun)
  File "/home/nofar/gatk-4.5.0.0/gatk", line 416, in runCommand
    check_call(cmd, env=gatk_env)
  File "/home/nofar/miniconda3/envs/mamba/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/nofar/miniconda3/envs/mamba/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/nofar/miniconda3/envs/mamba/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/nofar/miniconda3/envs/mamba/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```
The bam file as it named in the command line is accurate to my directory. I don't understand what is the problem, and I would like to get help :) 
Thanks in advance, 

Nofar :-]

**Comment by hadasvolk** [comment]
Hello Nofar, why are the filenames are inside quotation marks? Is it needed?
The error seems to be due to missing input bam file. Are you able to view the file using samtools view in the current directory?

**Comment by hadasvolk** [comment]
@ranelmalka100 I assume this has been resolved for you
